### ISSUE TITLE
Cannot import PyPlot in Julia 0.4.5

### ISSUE THREAD

**Issue by Azzoubeir** [stevengj/PyPlot.jl#224]
I have installed Julia in Windows OS but I cannot execute PyPlot. When I run 
`using PyPlot;`
I get the following exception

```
INFO: Precompiling module PyPlot...
ERROR: LoadError: InitError: error compiling __init__: could not load library "python27"
no error
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:235
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
during initialization of module PyCall
while loading C:\Users\Zou\.julia\v0.4\PyPlot\src\PyPlot.jl, in expression starting on line 5
Failed to precompile PyPlot to C:\Users\Zou\.julia\lib\v0.4\PyPlot.ji
in error at base\error.jl:21

```
I am using Anaconda for Python.

When I call `using PyCall;` I get
```
InitError: error compiling __init__: could not load library "python27"
no error
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:235
 [inlined code] from C:\Users\Zou\.julia\v0.4\Requires\src\require.jl:11
 in require at C:\Users\Zou\.julia\v0.4\Requires\src\hook.jl:17
 in include_string at loading.jl:288
 in eval at C:\Users\Zou\.julia\v0.4\Atom\src\Atom.jl:3
 [inlined code] from C:\Users\Zou\.julia\v0.4\Atom\src\eval.jl:39
 in anonymous at C:\Users\Zou\.julia\v0.4\Atom\src\eval.jl:108
 in withpath at C:\Users\Zou\.julia\v0.4\Requires\src\require.jl:37
 in withpath at C:\Users\Zou\.julia\v0.4\Atom\src\eval.jl:53
 [inlined code] from C:\Users\Zou\.julia\v0.4\Atom\src\eval.jl:107
 in anonymous at task.jl:58
during initialization of module PyCall
```

Any ideas how to fix this ?

**Comment by Azzoubeir** [comment]
I think this issue if about having Python 32-bit while Julia is 64-bit. So, now I installed Python 2.7 64-bit and I added it to the path but Julia is still pointing to Anaconda Python 32-bit not Python 64-bit. How can I get this fixed?

I did `ENV["PYTHON"]=""; Pkg.build("PyCall")` and got

```
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Traceback (most recent call last):
  File "C:\Users\Zou\.julia\v0.4\Conda\deps\usr\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Zou\.julia\v0.4\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 65, in main
    from conda.cli import conda_argparse
  File "C:\Users\Zou\.julia\v0.4\Conda\deps\usr\lib\site-packages\conda\cli\conda_argparse.py", line 17, in <module>
    from conda.cli import common
  File "C:\Users\Zou\.julia\v0.4\Conda\deps\usr\lib\site-packages\conda\cli\common.py", line 11, in <module>
    import conda.config as config
  File "C:\Users\Zou\.julia\v0.4\Conda\deps\usr\lib\site-packages\conda\config.py", line 16, in <module>
    from conda.compat import urlparse
  File "C:\Users\Zou\.julia\v0.4\Conda\deps\usr\lib\site-packages\conda\compat.py", line 42, in <module>
    from urllib import quote as urllib_quote
  File "C:\Users\Zou\AppData\Local\Continuum\Anaconda\Lib\urllib.py", line 26, in <module>
    import socket
  File "C:\Users\Zou\AppData\Local\Continuum\Anaconda\Lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.
```
